name: Build 🡢 Publish 🡢 Release (Linux Arm)

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
        matrix:
            include:
              - os: ubuntu-latest
                runtime: linux-arm
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Download IP2Location database
        run: |
            curl -L -o db.zip https://download.ip2location.com/lite/IP2LOCATION-LITE-DB1.CSV.ZIP
            unzip db.zip -d IpFilterLib/Databases

      - name: Strip PublishAot from .csproj file
        run: sed -i.bak '/<PublishAot>True<\/PublishAot>/d' IpFilterConsole/IpFilterConsole.csproj

      - name: Publish binary
        run: |
          dotnet publish IpFilterConsole/IpFilterConsole.csproj \
            -c Release \
            -r ${{ matrix.runtime }} \
            -p:Version=${{ env.VERSION }} \
            -o publish/${{ matrix.runtime }}

      - name: Zip binaries
        run: |
          zip -j IpFilterConsole-${{ matrix.runtime }}.zip publish/${{ matrix.runtime }}/*

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./IpFilterConsole-${{ matrix.runtime }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: VirusTotal Scan
        id: vt_linux-arm
        uses: crazy-max/ghaction-virustotal@v4
        with:
            vt_api_key: ${{ secrets.VT_API_KEY }}
            files: ./IpFilterConsole-${{ matrix.runtime }}.zip

      - name: Get release asset URL
        id: asset_linux-arm
        run: |
            asset_url=$(gh release view ${{ github.ref_name }} --json assets -q '.assets[] | select(.name == "./IpFilterConsole-${{ matrix.runtime }}.zip) | .url')
            echo "asset_url=$asset_url" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
            VT_LINK="${{ steps.vt_linux-arm.outputs.permalink }}"
            DL_LINK="${{ steps.asset_linux-arm.outputs.asset_url }}"
            sed -i "/build-linux-arm.yml\).*\|.*\|/c\\| [![Build 🡢 Publish 🡢 Release (Linux)](https://github.com/soyfrien/IpFilterGenerator/actions/workflows/build-linux-arm.yml/badge.svg)](https://github.com/soyfrien/IpFilterGenerator/actions/workflows/build-linux-arm.yml) | [Scan Result](${VT_LINK}) | [Download](${DL_LINK}) |" README.md