name: Build and Publish (Windows)

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
        matrix:
            include:
              - os: windows-latest
                runtime: win-x64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Download IP2Location database
        run: |
            curl -L -o db.zip https://download.ip2location.com/lite/IP2LOCATION-LITE-DB1.CSV.ZIP
            unzip db.zip -d IpFilterLib/Databases

      - name: Publish self-contained binary
        run: |
          dotnet publish IpFilterConsole/IpFilterConsole.csproj -c Release -r win-x64 -o publish/win-x64

      - name: Zip binaries
        run: |          
            Compress-Archive -Path publish/win-x64/IpFilterConsole.exe -DestinationPath IpFilterConsole-win-x64.zip

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            publish/win-x64/IpFilterConsole-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}