name: Build 🡢 Publish 🡢 Release (Linux Arm64)

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
        matrix:
            include:
              - os: ubuntu-latest
                runtime: linux-arm64
              - os: ubtuntu-latest
                runtime: linux-musl-arm64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Download IP2Location database
        run: |
            curl -L -o db.zip https://download.ip2location.com/lite/IP2LOCATION-LITE-DB1.CSV.ZIP
            unzip db.zip -d IpFilterLib/Databases

      - name: Add .NET ILCompiler
        run: sed -i '/<ItemGroup>/a \ <PackageReference Include="Microsoft.DotNet.ILCompiler; runtime.linux-arm64.Microsoft.DotNet.ILCompiler" Version="8.0.20" />' IpFilterConsole/IpFilterConsole.csproj

      - name: Add cross-compile support
        run: |
            sudo dpkg --add-architecture arm64
            sudo bash -c 'cat > /etc/apt/sources.list.d/arm64.list <<EOF
            deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ noble main restricted
            deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ noble-updates main restricted
            deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ noble-backports main restricted universe multiverse
            EOF'
            sudo sed -i -e 's/deb http/deb [arch=amd64] http/g' /etc/apt/sources.list
            sudo sed -i -e 's/deb mirror/deb [arch=amd64] mirror/g' /etc/apt/sources.list
            sudo apt update -qq
            sudo apt install -y clang llvm binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu zlib1g-dev:arm64

      - name: Publish self-contained binary
        run: |
          dotnet publish IpFilterConsole/IpFilterConsole.csproj \
            -c Release \
            -r ${{ matrix.runtime }} \
            --self-contained true \
            -p:Version=${{ env.VERSION }} \
            -o publish/${{ matrix.runtime }}

      - name: Zip binaries
        run: |
          zip -j IpFilterConsole-${{ matrix.runtime }}.zip publish/${{ matrix.runtime }}/*

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./IpFilterConsole-${{ matrix.runtime }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}